### ISSUE TITLE
Stuck On Pulling Docker Image from docker-compose.yml

### ISSUE THREAD

**Issue by ravics09** [cyberark/conjur-quickstart#39]
## Summary
Using Docker Desktop on Windows 10, When trying to pull image it stuck and not responding.
Tried to run below command 
$ docker-compose pull

After that it is not responding. 

## Steps to Reproduce
1. Clone the repo https://github.com/cyberark/conjur-quickstart.git
2. cd conjur-quickstart
3. docker-compose pull

## Expected Results
It should pulled the docker images defined in docker-compose.yml

## Actual Results (including error logs, if applicable)
After running the given command its not responding.

## Environment setup
Docker Desktop Community 3.1.0
Also tried on
Docker Desktop Community 2.5.0.1

**Comment by BradleyBoutcher** [comment]
Hi Ravi,

This sounds like it could be an issue with your docker daemon. Let's try a few things to troubleshoot:
- Run `docker-compose --verbose pull` to see verbose output, this may show why its hanging
- Can you verify that `docker-compose pull` is working with other configurations?
- Have you tried running `./test_workflow.sh` from the conjur-quickstart directory?
- If you run `docker-compose up bot-app`, is there output, or does it hang?

**Comment by ravics09** [comment]
Hi Bradley,

I tried to run 
> docker-compose --verbose pull

and getting below info
![dockerissue](https://user-images.githubusercontent.com/4203655/106664428-0f09d080-65cb-11eb-957d-15586c7bd957.png)

While running the below command

> docker-compose up bot-app

Getting Error: 
creating network "conjur-quickstart_default" with the default driver
**ERROR**: No such service: bot-app

**Comment by doodlesbykumbi** [comment]
@ravics09 Restarting your docker daemon might help resolve the `docker-compose pull` issue. After that you should be able to follow the rest of the [quick-start](https://github.com/cyberark/conjur-quickstart#set-up-a-conjur-oss-environment). 

> re: docker-compose up bot-app

That's failing because of a typo. The service is `bot_app`, instead of `bot-app`. You shouldn't need to bring up that service in isolation if you follow the rest of the [quick-start](https://github.com/cyberark/conjur-quickstart#set-up-a-conjur-oss-environment) once `docker-compose pull` succeeds.

**Comment by doodlesbykumbi** [comment]
For what it's worth, I've just successfully run through the flow on a fresh checkout of the repo on Windows.

**Comment by doodlesbykumbi** [comment]
Closing this now, please reopen and let us know if the issues persists.
